const I18N_LANGUAGES = {
  es: {
    "nav.inicio": "Inicio", "nav.labanda": "La banda", "nav.formacion": "Formación",
    "nav.musica": "Música", "nav.tocatas": "Tocatas", "nav.videos": "Videos",
    "nav.galeria": "Galería", "nav.contacto": "Contacto",
    "hero.tagline": "Thrash Metal · Talca, Chile",
    "hero.sub": "Riffs old school, doble guitarra filuda y actitud de barrio. Directo desde el Valle Central para machacar cualquier escenario.",
    "hero.btn.listen": "Escuchar el disco", "hero.btn.shows": "Ver tocatas", "hero.scroll": "Bajar",
    "band.eyebrow": "Nuestra historia", "band.title": "La Banda",
    "band.p1": "En las tierras agrícolas del Maule no solo crece trigo. Betrayer nació en <strong>Talca</strong> de las cenizas de otras bandas locales, con un único objetivo: hacer <strong>Thrash Metal</strong> sin asco, sin modas y directo al cráneo.",
    "band.p2": "Liricas desgarradoras, temáticas sociales e introspectivas y un sonido que te arranca los dientes. Así es Betrayer, la furia del sur.",
    "band.dt.origen": "Origen", "band.fact.origen": "Talca, Región del Maule, Chile",
    "band.dt.genero": "Género", "band.fact.genero": "Thrash Metal",
    "band.dt.disco": "Disco", "band.dt.grabado": "Grabado en",
    "band.dt.estado": "Estado", "band.fact.estado": "Banda activa",
    "lineup.eyebrow": "La formación actual", "lineup.title": "Quiénes somos",
    "lineup.role.voz": "Voz", "lineup.role.guitarra": "Guitarra", "lineup.role.bajo": "Bajo", "lineup.role.bateria": "Batería",
    "music.eyebrow": "Discografía", "music.title": "Música",
    "music.desc": "Escucha nuestro material en plataformas de streaming o apóyanos directamente en Bandcamp.",
    "music.meta": "Betrayer LP · 2019 · 7 tracks · ~23 min",
    "music.recorded": "Grabado en Betrayer Records, Talca — febrero de 2019.",
    "music.spotify.text": "Síguenos en Spotify para no perderte nada nuevo.",
    "music.btn.spotify": "Abrir en Spotify",
    "shows.eyebrow": "En vivo", "shows.title": "Tocatas",
    "shows.desc": "No te quedes fuera del mosh. Estas son nuestras fechas confirmadas.",
    "videos.eyebrow": "Audiovisual", "videos.title": "Videos",
    "videos.desc": "Revisa nuestras presentaciones en vivo, sesiones y videoclips oficiales en nuestro canal de YouTube.",
    "videos.placeholder": "Agrega videos en data/videos.json",
    "gallery.eyebrow": "Backstage & escenario", "gallery.title": "Galería",
    "gallery.desc": "Registros de la masacre en vivo. ¿Tienes fotos de la banda? ¡Mándalas por redes sociales!",
    "gallery.empty": "Buscando material fotográfico...",
    "contact.eyebrow": "Booking y contacto", "contact.title": "Contacto",
    "contact.msg": "¿Quieres llevar a Betrayer a tu tocata, festival o radio? La forma más rápida de contactarnos es por Instagram o Facebook.",
    "contact.btn.ig": "Escribir por Instagram", "contact.loc": "Talca, Región del Maule, Chile",
    "footer.meta": "Betrayer · Talca, Maule, Chile", "footer.top": "Volver arriba ↑"
  },
  en: {
    "nav.inicio": "Home", "nav.labanda": "The Band", "nav.formacion": "Line-up",
    "nav.musica": "Music", "nav.tocatas": "Shows", "nav.videos": "Videos",
    "nav.galeria": "Gallery", "nav.contacto": "Contact",
    "hero.tagline": "Thrash Metal · Talca, Chile",
    "hero.sub": "Old school riffs, sharp double guitars, and neighborhood attitude. Straight from the Central Valley to crush any stage.",
    "hero.btn.listen": "Listen to the album", "hero.btn.shows": "View shows", "hero.scroll": "Scroll down",
    "band.eyebrow": "Our history", "band.title": "The Band",
    "band.p1": "Wheat isn't the only thing that grows in the agricultural lands of Maule. Betrayer was born in <strong>Talca</strong> from the ashes of other local bands, with a single goal: to play <strong>Thrash Metal</strong> with no compromises, no trends, and straight to the skull.",
    "band.p2": "Gut-wrenching lyrics, social and introspective themes, and a sound that tears your teeth out. That's Betrayer, the fury of the south.",
    "band.dt.origen": "Origin", "band.fact.origen": "Talca, Maule Region, Chile",
    "band.dt.genero": "Genre", "band.fact.genero": "Thrash Metal",
    "band.dt.disco": "Album", "band.dt.grabado": "Recorded at",
    "band.dt.estado": "Status", "band.fact.estado": "Active",
    "lineup.eyebrow": "Current Line-up", "lineup.title": "Who we are",
    "lineup.role.voz": "Vocals", "lineup.role.guitarra": "Guitar", "lineup.role.bajo": "Bass", "lineup.role.bateria": "Drums",
    "music.eyebrow": "Discography", "music.title": "Music",
    "music.desc": "Listen to our material on streaming platforms or support us directly on Bandcamp.",
    "music.meta": "Betrayer LP · 2019 · 7 tracks · ~23 min",
    "music.recorded": "Recorded at Betrayer Records, Talca — February 2019.",
    "music.spotify.text": "Follow us on Spotify so you don't miss anything new.",
    "music.btn.spotify": "Open in Spotify",
    "shows.eyebrow": "Live", "shows.title": "Upcoming Shows",
    "shows.desc": "Don't miss the mosh pit. These are our confirmed dates.",
    "videos.eyebrow": "Audiovisual", "videos.title": "Videos",
    "videos.desc": "Check out our live performances, sessions, and official music videos on our YouTube channel.",
    "videos.placeholder": "Add videos in data/videos.json",
    "gallery.eyebrow": "Backstage & stage", "gallery.title": "Gallery",
    "gallery.desc": "Records of the live massacre. Do you have photos of the band? Send them through social media!",
    "gallery.empty": "Looking for photographic material...",
    "contact.eyebrow": "Booking and contact", "contact.title": "Contact",
    "contact.msg": "Want to bring Betrayer to your gig, festival, or radio? The fastest way to contact us is through Instagram or Facebook.",
    "contact.btn.ig": "Message on Instagram", "contact.loc": "Talca, Maule Region, Chile",
    "footer.meta": "Betrayer · Talca, Maule, Chile", "footer.top": "Back to top ↑"
  },
  de: {
    "nav.inicio": "Startseite", "nav.labanda": "Die Band", "nav.formacion": "Besetzung",
    "nav.musica": "Musik", "nav.tocatas": "Konzerte", "nav.videos": "Videos",
    "nav.galeria": "Galerie", "nav.contacto": "Kontakt",
    "hero.tagline": "Thrash Metal · Talca, Chile",
    "hero.sub": "Old-School-Riffs, scharfe Doppelgitarren und echte Straßen-Attitüde. Direkt aus dem Central Valley, um jede Bühne zu zerlegen.",
    "hero.btn.listen": "Album anhören", "hero.btn.shows": "Konzerte ansehen", "hero.scroll": "Runterscrollen",
    "band.eyebrow": "Unsere Geschichte", "band.title": "Die Band",
    "band.p1": "In den landwirtschaftlichen Gebieten von Maule wächst nicht nur Weizen. Betrayer entstand in <strong>Talca</strong> aus der Asche lokaler Bands, mit nur einem Ziel: <strong>Thrash Metal</strong> ohne Kompromisse, ohne Trends und direkt in die Fresse.",
    "band.p2": "Herzzerreißende Texte, soziale und introspektive Themen und ein Sound, der dir die Zähne ausschlägt. Das ist Betrayer, die Wut des Südens.",
    "band.dt.origen": "Herkunft", "band.fact.origen": "Talca, Region Maule, Chile",
    "band.dt.genero": "Genre", "band.fact.genero": "Thrash Metal",
    "band.dt.disco": "Album", "band.dt.grabado": "Aufgenommen in",
    "band.dt.estado": "Status", "band.fact.estado": "Aktiv",
    "lineup.eyebrow": "Aktuelle Besetzung", "lineup.title": "Wer wir sind",
    "lineup.role.voz": "Gesang", "lineup.role.guitarra": "Gitarre", "lineup.role.bajo": "Bass", "lineup.role.bateria": "Schlagzeug",
    "music.eyebrow": "Diskografie", "music.title": "Musik",
    "music.desc": "Hör dir unser Material auf Streaming-Plattformen an oder unterstütze uns direkt auf Bandcamp.",
    "music.meta": "Betrayer LP · 2019 · 7 Tracks · ~23 Min",
    "music.recorded": "Aufgenommen in den Betrayer Records, Talca — Februar 2019.",
    "music.spotify.text": "Folge uns auf Spotify, um nichts Neues zu verpassen.",
    "music.btn.spotify": "In Spotify öffnen",
    "shows.eyebrow": "Live", "shows.title": "Kommende Konzerte",
    "shows.desc": "Verpass den Moshpit nicht. Das sind unsere bestätigten Termine.",
    "videos.eyebrow": "Audiovisuell", "videos.title": "Videos",
    "videos.desc": "Sieh dir unsere Live-Auftritte, Sessions und offiziellen Musikvideos auf unserem YouTube-Kanal an.",
    "videos.placeholder": "Füge Videos in data/videos.json hinzu",
    "gallery.eyebrow": "Backstage & Bühne", "gallery.title": "Galerie",
    "gallery.desc": "Aufzeichnungen des Live-Massakers. Hast du Fotos von der Band? Schick sie über Social Media!",
    "gallery.empty": "Suche nach Fotomaterial...",
    "contact.eyebrow": "Booking und Kontakt", "contact.title": "Kontakt",
    "contact.msg": "Willst du Betrayer für dein Konzert, Festival oder Radio buchen? Der schnellste Weg uns zu kontaktieren ist über Instagram oder Facebook.",
    "contact.btn.ig": "Auf Instagram schreiben", "contact.loc": "Talca, Region Maule, Chile",
    "footer.meta": "Betrayer · Talca, Maule, Chile", "footer.top": "Nach oben ↑"
  },
  fr: {
    "nav.inicio": "Accueil", "nav.labanda": "Le Groupe", "nav.formacion": "Formation",
    "nav.musica": "Musique", "nav.tocatas": "Concerts", "nav.videos": "Vidéos",
    "nav.galeria": "Galerie", "nav.contacto": "Contact",
    "hero.tagline": "Thrash Metal · Talca, Chili",
    "hero.sub": "Riffs old school, doubles guitares tranchantes et attitude de quartier. Directement de la vallée centrale pour écraser n'importe quelle scène.",
    "hero.btn.listen": "Écouter l'album", "hero.btn.shows": "Voir les concerts", "hero.scroll": "Descendre",
    "band.eyebrow": "Notre histoire", "band.title": "Le Groupe",
    "band.p1": "Il n'y a pas que le blé qui pousse dans les terres agricoles du Maule. Betrayer est né à <strong>Talca</strong> des cendres d'autres groupes locaux, avec un seul but : faire du <strong>Thrash Metal</strong> sans compromis, sans modes et directement dans le crâne.",
    "band.p2": "Des paroles déchirantes, des thèmes sociaux et introspectifs, et un son qui vous arrache les dents. C'est Betrayer, la fureur du sud.",
    "band.dt.origen": "Origine", "band.fact.origen": "Talca, Région du Maule, Chili",
    "band.dt.genero": "Genre", "band.fact.genero": "Thrash Metal",
    "band.dt.disco": "Album", "band.dt.grabado": "Enregistré à",
    "band.dt.estado": "Statut", "band.fact.estado": "Actif",
    "lineup.eyebrow": "Formation actuelle", "lineup.title": "Qui sommes-nous",
    "lineup.role.voz": "Chant", "lineup.role.guitarra": "Guitare", "lineup.role.bajo": "Basse", "lineup.role.bateria": "Batterie",
    "music.eyebrow": "Discographie", "music.title": "Musique",
    "music.desc": "Écoutez notre matériel sur les plateformes de streaming ou soutenez-nous directement sur Bandcamp.",
    "music.meta": "Betrayer LP · 2019 · 7 pistes · ~23 min",
    "music.recorded": "Enregistré à Betrayer Records, Talca — février 2019.",
    "music.spotify.text": "Suivez-nous sur Spotify pour ne rien manquer.",
    "music.btn.spotify": "Ouvrir dans Spotify",
    "shows.eyebrow": "En direct", "shows.title": "Prochains concerts",
    "shows.desc": "Ne manquez pas le mosh pit. Voici nos dates confirmées.",
    "videos.eyebrow": "Audiovisuel", "videos.title": "Vidéos",
    "videos.desc": "Découvrez nos performances en direct, sessions et clips officiels sur notre chaîne YouTube.",
    "videos.placeholder": "Ajouter des vidéos dans data/videos.json",
    "gallery.eyebrow": "Backstage & scène", "gallery.title": "Galerie",
    "gallery.desc": "Enregistrements du massacre en direct. Avez-vous des photos du groupe ? Envoyez-les sur les réseaux sociaux !",
    "gallery.empty": "Recherche de matériel photographique...",
    "contact.eyebrow": "Réservation et contact", "contact.title": "Contact",
    "contact.msg": "Vous voulez amener Betrayer à votre concert, festival ou radio ? Le moyen le plus rapide de nous contacter est via Instagram ou Facebook.",
    "contact.btn.ig": "Écrire sur Instagram", "contact.loc": "Talca, Région du Maule, Chili",
    "footer.meta": "Betrayer · Talca, Maule, Chili", "footer.top": "Retour en haut ↑"
  },
  it: {
    "nav.inicio": "Home", "nav.labanda": "La Band", "nav.formacion": "Formazione",
    "nav.musica": "Musica", "nav.tocatas": "Concerti", "nav.videos": "Video",
    "nav.galeria": "Galleria", "nav.contacto": "Contatti",
    "hero.tagline": "Thrash Metal · Talca, Cile",
    "hero.sub": "Riff old school, doppie chitarre taglienti e attitudine di strada. Direttamente dalla Valle Centrale per distruggere qualsiasi palco.",
    "hero.btn.listen": "Ascolta l'album", "hero.btn.shows": "Vedi concerti", "hero.scroll": "Scorri giù",
    "band.eyebrow": "La nostra storia", "band.title": "La Band",
    "band.p1": "Non cresce solo grano nelle terre agricole del Maule. I Betrayer sono nati a <strong>Talca</strong> dalle ceneri di altre band locali, con un unico obiettivo: fare <strong>Thrash Metal</strong> senza compromessi, senza mode e dritto al cranio.",
    "band.p2": "Testi strazianti, temi sociali e introspettivi e un suono che ti strappa i denti. Questo è Betrayer, la furia del sud.",
    "band.dt.origen": "Origine", "band.fact.origen": "Talca, Regione del Maule, Cile",
    "band.dt.genero": "Genere", "band.fact.genero": "Thrash Metal",
    "band.dt.disco": "Album", "band.dt.grabado": "Registrato a",
    "band.dt.estado": "Stato", "band.fact.estado": "Attivi",
    "lineup.eyebrow": "Formazione attuale", "lineup.title": "Chi siamo",
    "lineup.role.voz": "Voce", "lineup.role.guitarra": "Chitarra", "lineup.role.bajo": "Basso", "lineup.role.bateria": "Batteria",
    "music.eyebrow": "Discografia", "music.title": "Musica",
    "music.desc": "Ascolta il nostro materiale sulle piattaforme di streaming o supportaci direttamente su Bandcamp.",
    "music.meta": "Betrayer LP · 2019 · 7 tracce · ~23 min",
    "music.recorded": "Registrato ai Betrayer Records, Talca — febbraio 2019.",
    "music.spotify.text": "Seguici su Spotify per non perdere le novità.",
    "music.btn.spotify": "Apri in Spotify",
    "shows.eyebrow": "Dal vivo", "shows.title": "Prossimi Concerti",
    "shows.desc": "Non restare fuori dal mosh. Queste sono le nostre date confermate.",
    "videos.eyebrow": "Audiovisivo", "videos.title": "Video",
    "videos.desc": "Guarda le nostre esibizioni dal vivo, le sessioni e i video musicali ufficiali sul nostro canale YouTube.",
    "videos.placeholder": "Aggiungi video in data/videos.json",
    "gallery.eyebrow": "Backstage & palco", "gallery.title": "Galleria",
    "gallery.desc": "Registrazioni del massacro dal vivo. Hai foto della band? Inviale tramite i social media!",
    "gallery.empty": "Ricerca di materiale fotografico in corso...",
    "contact.eyebrow": "Booking e contatti", "contact.title": "Contatti",
    "contact.msg": "Vuoi portare i Betrayer al tuo concerto, festival o in radio? Il modo più veloce per contattarci è tramite Instagram o Facebook.",
    "contact.btn.ig": "Scrivi su Instagram", "contact.loc": "Talca, Regione del Maule, Cile",
    "footer.meta": "Betrayer · Talca, Maule, Cile", "footer.top": "Torna su ↑"
  },
  uk: {
    "nav.inicio": "Головна", "nav.labanda": "Гурт", "nav.formacion": "Склад",
    "nav.musica": "Музика", "nav.tocatas": "Концерти", "nav.videos": "Відео",
    "nav.galeria": "Галерея", "nav.contacto": "Контакти",
    "hero.tagline": "Thrash Metal · Талька, Чилі",
    "hero.sub": "Рифи старої школи, гострі подвійні гітари та справжній вуличний настрій. Прямо з Центральної долини, щоб зруйнувати будь-яку сцену.",
    "hero.btn.listen": "Слухати альбом", "hero.btn.shows": "Концерти", "hero.scroll": "Вниз",
    "band.eyebrow": "Наша історія", "band.title": "Гурт",
    "band.p1": "На сільськогосподарських землях Мауле росте не лише пшениця. Betrayer народилися в <strong>Тальці</strong> з попелу інших місцевих гуртів з єдиною метою: грати <strong>Thrash Metal</strong> без компромісів, без трендів і прямо в череп.",
    "band.p2": "Щемливі тексти, соціальні та інтроспективні теми і звук, що вириває зуби. Це Betrayer — лють півдня.",
    "band.dt.origen": "Походження", "band.fact.origen": "Талька, Регіон Мауле, Чилі",
    "band.dt.genero": "Жанр", "band.fact.genero": "Thrash Metal",
    "band.dt.disco": "Альбом", "band.dt.grabado": "Записано в",
    "band.dt.estado": "Статус", "band.fact.estado": "Активні",
    "lineup.eyebrow": "Поточний склад", "lineup.title": "Хто ми",
    "lineup.role.voz": "Вокал", "lineup.role.guitarra": "Гітара", "lineup.role.bajo": "Бас", "lineup.role.bateria": "Барабани",
    "music.eyebrow": "Дискографія", "music.title": "Музика",
    "music.desc": "Слухайте наш матеріал на стрімінгових платформах або підтримайте нас безпосередньо на Bandcamp.",
    "music.meta": "Betrayer LP · 2019 · 7 треків · ~23 хв",
    "music.recorded": "Записано в Betrayer Records, Талька — лютий 2019.",
    "music.spotify.text": "Слідкуйте за нами в Spotify, щоб не пропустити новинки.",
    "music.btn.spotify": "Відкрити в Spotify",
    "shows.eyebrow": "Наживо", "shows.title": "Концерти",
    "shows.desc": "Не пропусти мош. Це наші підтверджені дати.",
    "videos.eyebrow": "Аудіовізуальні", "videos.title": "Відео",
    "videos.desc": "Дивіться наші живі виступи, сесії та офіційні відеокліпи на нашому YouTube-каналі.",
    "videos.placeholder": "Додайте відео в data/videos.json",
    "gallery.eyebrow": "За лаштунками та на сцені", "gallery.title": "Галерея",
    "gallery.desc": "Записи живого розгрому. Маєте фото гурту? Надсилайте їх через соціальні мережі!",
    "gallery.empty": "Пошук фотоматеріалів...",
    "contact.eyebrow": "Букінг та контакти", "contact.title": "Контакти",
    "contact.msg": "Хочете запросити Betrayer на свій концерт, фестиваль чи радіо? Найшвидший спосіб зв'язатися з нами — через Instagram або Facebook.",
    "contact.btn.ig": "Написати в Instagram", "contact.loc": "Талька, Регіон Мауле, Чилі",
    "footer.meta": "Betrayer · Талька, Мауле, Чилі", "footer.top": "Вгору ↑"
  }
};
